language: generic

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: never

cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm/.cache

branches:
  only:
    - master

env:
  global:
    - BLOCK_SLUG: block-a-saurus

before_install:
  - nvm install --latest-npm
  - |
    # Upgrade docker-compose.
    sudo rm /usr/local/bin/docker-compose
    curl -sL https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > docker-compose
    chmod +x docker-compose
    sudo mv docker-compose /usr/local/bin

install:
  - npm ci
  - |
    echo '{ "config": { "WP_DEBUG": true, "SCRIPT_DEBUG": false, "WP_PHP_BINARY": "php", "WP_TESTS_EMAIL": "admin@example.org", "WP_TESTS_TITLE": "Test Blog" }, "plugins":[ "https://downloads.wordpress.org/plugin/'$BLOCK_SLUG'.latest-stable.zip" ] }' > .wp-env.override.json
    chmod -R 767 ./ 
    npm run wp-env start

jobs:
  include:
    - name: Testing
      script:
        - docker ps -a
        - curl -i http://localhost:8888/
        - npm run wp-env run cli wp plugin list
