# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test-block"
  test-block:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      BLOCK: block-a-saurus

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install
      run: |
        nvm install --latest-npm
        npm ci
        echo '{ "config": { "WP_DEBUG": true, "SCRIPT_DEBUG": false, "WP_PHP_BINARY": "php", "WP_TESTS_EMAIL": "admin@example.org", "WP_TESTS_TITLE": "Test Blog" }, "plugins":[ "https://downloads.wordpress.org/plugin/'$BLOCK_SLUG'.latest-stable.zip" ] }' > .wp-env.override.json
        chmod -R 767 ./
        npm run wp-env start

    - name: Test it all.
      run: |
        curl -i http://localhost:8888/
        npm run wp-env run cli wp plugin list
        docker ps -a

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
